baseURL = "http://blog.opinionatedapps.com/"
languageCode = "en-us"
title = "Opinionatedapps blog"
theme = "ananke"
disqusShortname = "opinionatedapps"
[params]
  body_classes = "avenir bg-near-white"
  background_color_class = "bg-dark-green"
